"use strict";
let places = ["Switzerland", "Natherland", "Japan", "UK", "New-zeland"];
console.log(places);
console.log(["Switzerland", "Natherland", "Japan", "UK", "New-zeland"].sort());
console.log(places);
console.log(["Switzerland", "Natherland", "Japan", "UK", "New-zeland"].sort().reverse());
console.log(places);
console.log(places.reverse());
console.log(places.reverse());
console.log(places.sort());
console.log(places.sort().reverse());
